### DISCUSSION TITLE
Git-friendly scene files

### DISCUSSION THREAD

**Discussion by YerkoAndrei** [stride3d/stride#2115] [Ideas]
I think scenes files should only use the GUID for referencing prefabs.

Right now, the scene saves everything of a prefab used on it, but with this format its very hard to work with a lot of people.

Say someone is working on the prefabs and another is on the scene, when the prefab is edited, it also edited any scene that use it, not so team-friendly.

I dont know how hard is to implement this, its just a suggestion. :)

**Comment by Doprez** [comment]
I would be curious as to what the standard is in other engines? 

Is your suggestion to use the prefab as the source of truth or to only use it for instantiation and have the scene handle the values?

I personally like that when I edit a prefab I can expect it to change any of the references that are in a scene but I purely use this as a fun hobby and as a solo dev so Im not sure what other people may expect or want.

**Reply by YerkoAndrei** [reply]
I have worked in unity with teams and the workflow a lot of time was a person editing a scene and another some prefabs, or one editing the enviroment prefab, and another the characer prefab, as an example.

My idea is to do that possible, but does not include not being able to change some prefab values in a scene (Unity saves the GUID and the changes of the prefab in that scene, Stride saves everything the prefab has, including changes).

**Reply by Doprez** [reply]
Ah ok, that makes sense. So it would cut down on the amount of merge conflicts created from having all of the unedited data of a prefab being saved?

**Reply by YerkoAndrei** [reply]
exatly

**Reply by Doprez** [reply]
I think this makes a lot of sense. 

Tagging @manio143 and @IXLLEGACYIXL since they may have some helpful input on this with their serialization knowledge.

**Reply by manio143** [reply]
I think the reason it's currently implemented as a full object copy into the scene is to save on prefab lookup during asset initialization. The scene asset is independent of the prefab asset, except when your editing the prefab and need to propagate the changes. Otherwise, when compiling a scene you need to make sure you have a reference to the prefab to merge the properties. And with nested prefabs you'd need some kind of caching of the merged layers to make it performant and not do merging all the way down every time.

That is not to say that this is how it should be. I agree that having just changed properties could be easier for source control. The current archetype system has been designed in a specific way across a few different editor/serialization modules and we'd need to understand how it could be modified.

You may want to ping Kryptos for some historical context.

**Reply by Kryptos-FR** [reply]
I don't think it is feasible to just have the object id. We wouldn't be able to support nested prefabs or the fact that you can override only a part of it, if the whole structure wasn't copied over.

Our prefabs support more use cases than Unity, so comparing with it isn't the whole picture.

I understand the potential issue with team work, but it isn't simple to do it differently. It wasn't done just as a way to make it faster to resolve. And also, as was written it is sharing that mechanism with archetype. It's not trivial to change that.

**Comment by IXLLEGACYIXL** [comment]
how do you imagine a yaml to look and how it should be resolved , also which values should be serialized, how should default values be evaluated and such

what is the dream case you can imagine it to be

**Reply by YerkoAndrei** [reply]
I think that only the ID and the changes should be serialized.
I dont know how unity load everything, but when you add a prefab in a scene, it only add the GUID.
I imagine that Unity search for that and it load it after the scene.

I can only tell how i worked with Unity, because that way never gave me a problem, which i know i'll have if i work with Stride with a team.

In this Unity scene, the first GameObjet is a prefab and the second not, and only saves the id of the prefab, it doesnt have changes.
```
GameObject:
  m_CorrespondingSourceObject: {fileID: 2853423567576865651, guid: b29aac657b977e94aa5d0a01f4b7d7b0, type: 3}
  m_PrefabInstance: {fileID: 1920324864}
  m_PrefabAsset: {fileID: 0}
--- !u!1 &120897676
GameObject:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 120897678}
  - component: {fileID: 120897677}
  m_Layer: 0
  m_Name: "SistemaAnimaci\xF3n"
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 4294967295
  m_IsActive: 1
--- !u!114 &120897677
```
And in Stride it saves everything, this have a changes (the Deleted ones).
```
-   Folder: null
            Entity:
                Id: 07607ce9-1595-403c-aeb4-a9249831f41b
                Name: Estatua
                Components:
                    1ff5b84f1e279da93224f2a5edcc3f59: !TransformComponent
                        Id: 9d21e8a8-712c-4ff4-9265-f117b4b6168f
                        Position*: {X: 0.0, Y: 0.0, Z: -5.0}
                        Rotation: {X: 0.0, Y: 0.0, Z: 0.0, W: 1.0}
                        Scale: {X: 1.0, Y: 1.0, Z: 1.0}
                        Children:
                            b9a6de9d3e362d0511a1a20a34248d55: ref!! 93a6666b-a85e-4f79-9908-ae6c6c2d7725
                    65e0ce82b10ff7a08a25a37be73a73db: ~(Deleted)
                    fb06c492109ce5cf0499d7d8846d1f46: ~(Deleted)
                    74bf11dd4dd7e8fa7f6dd5d9df36ec37: ~(Deleted)
            Base:
                BasePartAsset: c957f17f-b857-4560-8c7f-74977bd833cf:Prefabs/Estatua
                BasePartId: 56f5ad60-3d77-4bf7-9c13-cbb046c76088
                InstanceId: 0b77de18-b5b0-46a5-a7ad-e7ec37e4047c
```
