### ISSUE TITLE
GameStudio to discover IProceduralModel classes from project files.

### ISSUE THREAD

**Issue by tagcode** [stride3d/stride#1583]
Game Studio cannot discover exported _IProceduralModel_ classes from project, only the built-in ones.

<img width="513" alt="gamestudio" src="https://user-images.githubusercontent.com/5236113/212058023-e84639ba-87b6-41c5-8586-22a623abbfda.png">

Could the Game Studio be updated so that is scans for the exported _IProceduralModel_ classes from the managed .dll files, and adds them to the Asset menu. The scanning part is should be easy to do with [Mono.Cecil](https://github.com/jbevain/cecil/) which can enumerate anything inside managed .dll without loading into appdomain.

**Comment by tagcode** [comment]
I just noticed that this dropdown menu does discover all the procedural model classes. So it's only that asset menu that doesn't. 

![stride](https://user-images.githubusercontent.com/5236113/212473326-eb98e735-9508-4ccb-8075-dc70542b52f1.png)

As workaround trick, I can create a model from a built-in procedure, e.g. Plane, and then change it from this dropdown menu.

**Comment by mattiascibien** [comment]
As far as I saw by studying the code there are some different approaches with the Asset Window and the Property Grid. The property grid looks for the Types in every assembly or DLL while the Asset Window uses YAML templates like this in order to be discovered:
```yaml
# FILE: Stride.Assets.Presentation\Templates\Assets\Models\ProceduralCube.sdtpl
!TemplateAssetFactory
Id: 8267F08C-3DC8-48F4-81EA-4888A1CEF9CE
AssetTypeName: ProceduralModelAsset
Name: Cube
Scope: Asset
Description: A procedurally-generated cube
Group: Model
Order: 20
Icon: ..\.sdtpl\ProceduralCube.png
DefaultOutputName: Cube
FactoryTypeName: ProceduralModelCubeFactory
```

I guess that if you add a template file like this one to your proect and implement the factory by implementing ` AssetFactory<ProceduralModelAsset>` and specifying it in the `FactoryTypeName` of your template you can make your procedural model appear in the new Asset Window
